[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin build --release"
[tool.maturin]
bindings = "pyo3"
features = ["python"]
[project]
name = "seuif97"
version = "2.3.5"
description = "The high-speed IAPWS-IF97 package in Rust with Python bindings"
readme = "README_Python.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Cheng Maohua", email = "cmh@seu.edu.cn"}
]
keywords = ["IF97", "IAPWS-IF97", "thermodynamics"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "Operating System :: OS Independent",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/thermalogic/"
Repository = "https://github.com/thermalogic/RustSEUIF97/"
