name: Build Windows DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Build DLL
      run: cargo build --release --features stdcall --crate-type cdylib
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: seuif97-dll
        path: target/release/seuif97.dll
