name: Build Linux C Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Build C dynamic library
      run: cargo build --release --features cdecl --crate-type cdylib
    - name: Create output directory
      run: mkdir -p target/release/lib
    - name: Copy library
      run: cp target/release/libseuif97.so target/release/lib/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: seuif97-c-lib
        path: |
          target/release/libseuif97.so
          target/release/lib/libseuif97.so
